theme = "custom1"
title = "Taylor Brazelton"
baseURL = "https://taylorbrazelton.com"
outputFolder = "docs"

types = ["post", "page"]

post.dateInURL = true
post.sortBy = "date"
post.sortReverse = true

page.dateInURL = false
page.sortBy = "title"
page.sortReverse = false
